# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build GymBros App
        run: |
          cd GymBros
          xcodebuild -project GymBros.xcodeproj \
                     -scheme GymBros \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     build
   # - name: Run tests
      # run: swift test -v
      
